[project]
name = "IoT"
version = "0.1.0"
description = ""
authors = [
    { name = "Pascal Helfenstein", email = "pascal.helfenstein@xemax.ch" },
]
requires-python = ">=3.13"
readme = "README.md"
dependencies = [
    "python-dotenv>=1.1.1",
    "pydantic-settings>=2.11.0",
    "pydantic>=2.12.3",
    "rich>=14.2.0",
    "pydantic-ai>=1.23.0",
    "httpx>=0.28.1",
]

[tool.pytest.ini_options]
pythonpath = "."
